version: '3.8'

services:
  corenlp:
    image: nlpbox/corenlp
    platform: linux/amd64
    environment:
      - JAVA_XMX=4g
    ports:
      - "9000:9000"

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - corenlp
    command: python graphSAGE_rag_visualization.py